### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by PedroHLC** [flightlessmango/PKGBUILDS#2]
When building in a clean chroot it fails with:
```
Build-time dependency wayland-scanner found: NO (tried pkgconfig)

meson.build:1542:2: ERROR: Dependency "wayland-scanner" not found, tried pkgconfig
```
this executable is owned by `wayland` package, as it's mentioned as "build-time dependency" `makedepends` seems nice.

```
Run-time dependency wayland-protocols found: NO (tried pkgconfig)

meson.build:1549:2: ERROR: Dependency "wayland-protocols" not found, tried pkgconfig
```
So `wayland-protocols` must be added as a dependency.

```
Run-time dependency xext found: NO (tried pkgconfig)

meson.build:1590:4: ERROR: Dependency "xext" not found, tried pkgconfig
```
Would be: `libxext`.

```
Run-time dependency xdamage found: NO (tried pkgconfig)

meson.build:1591:4: ERROR: Dependency "xdamage" not found, tried pkgconfig
```
`libxdamage`.

```
Run-time dependency xshmfence found: NO (tried pkgconfig)

meson.build:1617:6: ERROR: Dependency "xshmfence" not found, tried pkgconfig
``` 
`libxshmfence`

```
Run-time dependency xxf86vm found: NO (tried pkgconfig)

meson.build:1626:6: ERROR: Dependency "xxf86vm" not found, tried pkgconfig
```
`libxxf86vm`

And: `libxrandr`

Of course, **all the lib32** corresponding too.
The correct would be to put everything in makedepends, and copy the libs to depends on the correct package function.

**Comment by telans** [comment]
Thanks, how does #3 look to you? I'm honestly not too sure what dependencies the overlay requires aside from what you've listed here.
